---
- name: Deploy and manage Nginx container
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    container_name: webserver_prod
    image_name: nginx:latest
    host_port: 8080
    docker_env:
      DOCKER_HOST: "unix:///var/run/docker.sock"

  tasks:
    - name: Ensure Docker service is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the latest Nginx image
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull
      environment: "{{ docker_env }}"

    - name: Create and run the Nginx container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "{{ host_port }}:80"
      environment: "{{ docker_env }}"



